apiVersion: skaffold/v4beta1
kind: Config
metadata: 
  name: skaffold-clouddeploy-test
requires:
  - configs:
    - kustomize
    path: modules/kustomize/skaffold.yaml
  - configs:
    - raw
    path: modules/raw/skaffold.yaml
  - configs:
    - helm-local
    path: modules/helm-local/skaffold.yaml
  - configs:
    - helm-remote
    path: modules/helm-remote/skaffold.yaml
  ## temporarily disabled due to https://github.com/GoogleContainerTools/skaffold/issues/8578
  # - configs:
  #   - kpt
  #   path: modules/kpt/skaffold.yaml
  ## temporarily disabled due to https://github.com/GoogleContainerTools/skaffold/issues/8579
  # - configs:
  #   - manifests-transform
  #   path: modules/manifests-transform/skaffold.yaml
