apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: kustomize
requires:
  - configs:
    - namespace
    path: ../../shared/manifests/skaffold.yaml
profiles:
  - name: kustomize-simple
    manifests:
      kustomize:
        paths:
        - k8s/overlays/simple
      output: render/result.yaml # TODO: create bug - this does nothing
    test:
      - image: hello
        custom:
        - command: /bin/bash -c "diff golden_render.yaml <(skaffold render -p kustomize-simple -a ../../artifacts.json)"
    verify:
    - name: verify
      container:
        name: verify-http-status-200
        image: google/cloud-sdk:latest
        command: ["bin/bash"]
        args: ["-c", "gcloud container clusters get-credentials development --region us-central1 --project skaffold-clouddeploy-test && if [[ $(curl http://$(kubectl get service kustomize-local -n skaffold-clouddeploy-test -o jsonpath='{.status.loadBalancer.ingress[0].ip}') --write-out '%{http_code}'  --silent --head --output /dev/null) -ne '200' ]]; then exit 1; fi"]
