apiVersion: apps/v1
kind: Deployment
metadata:
  name: raw
  namespace: skaffold-clouddeploy-test
  labels:
    app: raw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raw
  template:
    metadata:
      labels:
        app: raw
    spec:
      containers:
      - name: hello
        image: hello
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080