apiVersion: v1
kind: Service
metadata:
  name: raw
  namespace: skaffold-clouddeploy-test
  labels:
    app: raw
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: http
