apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  {{- if .Values.namespace }}  
  namespace: {{ .Values.namespace }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: hello
        image: "{{ .Values.image }}"
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.containerPort }}