apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  {{- if .Values.namespace }}  
  namespace: {{ .Values.namespace }}
  {{- end }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: {{ .Values.containerPort }}
      name: http
  selector:
    app: {{ .Chart.Name }}
