apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: manifests-transform
requires:
  - configs:
    - namespace
    path: ../../shared/namespace/skaffold.yaml
manifests:
  rawYaml:
    - k8s/base/*
  transform: # TODO: create Bug this render breaks within gcr.io/k8s-skaffold/skaffold:v2.2.0 image!
    - name: set-labels
      configMap:
        - "app:manifests-transform"
    - name: create-setters
      configMap:
        - "name:kustomize"
    - name: apply-setters
      configMap:
        - "name:manifests-transform"
    # TODO: create bug - this exits with exitcode 1 -> namespace setting with transform seems to be broken
    # - name: create-setters
    #   configMap:
    #     - "namespace:skaffold-clouddeploy-test"
    # - name: apply-setters
    #   configMap:
    #     - "namespace:asdf"
    # TODO: create bug - this exits with exitcode 1 -> namespace setting with transform seems to be broken
    # - name: set-namespace 
    #   configMap:
    #     - "namespace:asdf"
  validate:
   - name: kubeval
  output: render/result.yaml # TODO: create bug - this does nothing
test:
  - image: hello
    custom:
    - command: /bin/bash -c "echo Testing module manifests-transform && diff golden_render.yaml <(skaffold render -a ../../artifacts.json)" 
verify:
- name: verify-manifests-transform
  container:
    name: verify-http-status-200-manifests-transform
    image: google/cloud-sdk:latest
    command: ["bin/bash"]
    args: ["-c", "gcloud container fleet memberships get-credentials gke-membership && if [[ $(curl http://$(kubectl get service manifests-transform -n skaffold-clouddeploy-test -o jsonpath='{.status.loadBalancer.ingress[0].ip}') --write-out '%{http_code}'  --silent --head --output /dev/null) -ne '200' ]]; then exit 1; fi"]
